# This is a github action.
name: Refesh from MWRA

# Run this workflow ever time code is pushed to a branch
# other than `main` in your repository
on: workflow_dispatch

jobs:
  refresh_from_mwra:
    name: Refesh Covid data from MWRA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - run: set
      - run: pwd
      - run: Rscript -e 'install.packages("rmarkdown")'
      - run: Rscript -e 'library(rmarkdown); rmarkdown::render("scrape_and_tidy.Rmd")'

# That it.
