# This is a github action.
name: Refesh from MWRA
branch: master

# Run this workflow ever time code is pushed to a branch
# other than `main` in your repository
on: workflow_dispatch

jobs:
  refresh_from_mwra:
    name: Refesh Covid data from MWRA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master   # see https://github.com/r-lib/actions/tree/master/examples
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      - shell: bash
        run: |
          date
          pwd
          set
      - shell: Rscript {0}
        run: |
          install.packages(c("rmarkdown", "readr", "devtools", "tidyverse", "urltools",
                             "rvest", "here", "feasts", "pdftools", "gridExtra"))
          library(rmarkdown); rmarkdown::render("scrape_and_tidy.Rmd")

# That it.
