# This is a github action.
name: Refesh from SARS-Covid-19 RNA samples from MWRA

# Run this workflow ever time code is pushed to a branch
# other than `main` in your repository
on: workflow_dispatch

jobs:
  refresh_from_mwra:
    name: Refesh Covid data from MWRA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master   # see https://github.com/r-lib/actions/tree/master/examples
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      - shell: bash
        run: |
          date
          pwd
          set
      - name: R depedencies # Do i need to do this seperately?
        shell: Rscript {0}
        run: |
          install.packages(c("devtools", "remotes"))
          remotes::install_deps(depenencies=TRUE)
      - name: system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: :linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreq')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "sysreqs"
      - name: R depedencies
        shell: Rscript {0}
        run: |
          install.packages(c("rmarkdown", "readr", "devtools", "tidyverse", "urltools"))
          install.packages(c("rvest", "here", "feasts", "pdftools", "gridExtra", "remotes"))
          remotes::install_deps(depenencies=TRUE)
      - name: do it
        shell: Rscript {0}
        run: |
          library(rmarkdown); rmarkdown::render("scrape_and_tidy.Rmd")

# That it.
